### ISSUE TITLE
About Linguistic features

### ISSUE THREAD

**Issue by CSSDStudioCXY** [flyingpig233-cpu/oi-debug#2]
Should we make full use of the new features of C++to achieve functions ?

**Comment by flyingpig233-cpu** [comment]
Hello. I think, the most important is to impelement the target.

**Comment by CSSDStudioCXY** [comment]
Kernel functions can be used for stack debugging, and C++does support kernel function ?

**Comment by CSSDStudioCXY** [comment]
C++ support kernel functions

**Comment by flyingpig233-cpu** [comment]
And so?

**Comment by CSSDStudioCXY** [comment]
6Wrong location

**Comment by CSSDStudioCXY** [comment]
It should be posted next door

**Comment by flyingpig233-cpu** [comment]
Yeah,...
