### ISSUE TITLE
About platform

### ISSUE THREAD

**Issue by CSSDStudioCXY** [flyingpig233-cpu/oi-debug#3]
Can we only support the Linux platform to use kernel functions such as printk, or determine the compilation platform through macros ?

**Comment by flyingpig233-cpu** [comment]
Hello. You may not very understand the meaning of `printk`, it runs under the core layer and just used for debug the kernel. This library do **NOT** need that.

**Comment by onion108** [comment]
> Can we only support the Linux platform to use kernel functions such as printk, or determine the compilation platform through macros ?

You are so yo8372645987678r638872973r87468659367r87236r8g6538f746crv81728vr761v77bh128c6rbit127r78c bro

**Comment by onion108** [comment]
Аи синк но шан шил реалаиз зат ит ис ацтуали ан Инглисч сентенсе /хых

**Comment by CSSDStudioCXY** [comment]
Kernel functions can be used for stack debugging, and C++ exactly support kernel function

**Comment by flyingpig233-cpu** [comment]
then? We do not need that.

**Comment by CSSDStudioCXY** [comment]
six
