### ISSUE TITLE
About project development prospect

### ISSUE THREAD

**Issue by CSSDStudioCXY** [flyingpig233-cpu/oi-debug#4]
I think it can be more than a multi-function output. So, do we need debug tools such as complexity analyzer and data generator?

**Comment by flyingpig233-cpu** [comment]
For example?

**Comment by CSSDStudioCXY** [comment]
《such as》《For example》

**Comment by flyingpig233-cpu** [comment]
I mean that you can point out a way to do

**Comment by CSSDStudioCXY** [comment]
Directly construct syntax tree to analyze complexity. And output the stack information of a program, as mentioned in the previous issue.

**Comment by flyingpig233-cpu** [comment]
It is the duty for the `gdb`

**Comment by CSSDStudioCXY** [comment]
six
